### ISSUE TITLE
As an installing Admin I want a single tab for my non-repetitive setup and admin tasks so that it is clear where to go do set up the app

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#1]
This story refers simply to the new custom VF tab for Echo Admin

AC:
- [x] Admin user can view a new VF tab named Echo Admin
- [x] Custom Profile Setting is updated to grant access to Echo Admin to SysAdmins - there is no custom profile setting in MIR3, noted for recommendations in Phase 2 - JE

**Comment by stevenFulgham** [comment]
I need to go over the profile settings with someone familiar with it. Just to be sure I did it right.
