### ISSUE TITLE
As an installing Admin I want a subtab that will guide me through the various workflow rules to be configured so that I can easily set up the app

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#10]
AC:
- [ ] Similar to Page Layouts, a button will open the New Workflow rule page in a new tab
- [ ] Subtab marks rules as completed when the user indicates as such

Frank liked a button for each rule to setup. I was thinking maybe a table or list of the rules and a description but just one button to initiate the creation of all rules in turn.

**Comment by stevenFulgham** [comment]
As soon as Rina has finished the new flow for Page Layouts, I will add the logic to the Workflow page.

**Comment by jengler74** [comment]
@rinaTaur I know we're copying the help window approach from Page Layouts to Workflow RUles but do we need to pull together the content for the WF help window still? i.e. some annotated screenshots of the rule criteria, the action, etc. ?
I think for page layouts you had made new ones for your user guide suggestions but not sure how we want to present the WF help

**Comment by rinaTaur** [comment]
@jengler74 I didn't fully build out the content for page layouts, just enough to establish a pattern. Workflow rules _should_ follow the same pattern pretty well. There are several screens in the document, along with textual steps. Is that something we need to be delivering in full? Or will their devs be pulling the full content of each of those into the helper window VF pages?

**Comment by jengler74** [comment]
It will be us. I don't want to rely on their devs. As you said, just a few
screenshots with textual steps.

On Tue, Apr 19, 2016 at 12:11 PM, Rina Henderson <notifications@github.com>
wrote:

> @jengler74 <https://github.com/jengler74> I didn't fully build out the
> content for page layouts, just enough to establish a pattern. Workflow
> rules *should* follow the same pattern pretty well. There are several
> screens in the document, along with textual steps. Is that something we
> need to be delivering in full? Or will their devs be pulling the full
> content of each of those into the helper window VF pages?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CodeScience/MIR3/issues/10#issuecomment-212073106>
>



-- 
Jeremy Engler | Director, ISV Product Management
_______________________

832 Cole Street

San Francisco, CA 94117

*C* 415-515-9429

*info@codescience.com* <hr@codescience.com>

*www.codescience.com <http://www.codescience.com/>*


*loathing cubicles since 2009* - We are hiring!
<http://codescience.com/careers/>
