### ISSUE TITLE
As an installing Admin I want a subtab where I can set up my Default Device Priority so that I can easily setup the app

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#11]
AC:
- [x] User has a subtab for Device Priority in the Admin tab
- [x] This is a persistent subtab which re-uses the same data model from within the current UI but updates the UI to SLDS
- [x] This subtab has Save and Save & Next buttons to allow saving before moving on

**Comment by jengler74** [comment]
@stevenFulgham Looks great. Some notes for this subtab and @rinaTaur , please validate. 
- [ ] On "Save" without Next, display a Success-level message. "Your changes have been saved."
- [ ] On "Save and Next" display a Success-level message on the next subtab with the same text.
- [ ] What does "Cancel" do?

**Comment by stevenFulgham** [comment]
Cancel should reset the form. Would you like to keep it or have it removed?
