### ISSUE TITLE
UX Feedback: Connect to MIR3

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#18]
There are two next buttons when viewing a trial configuration. Frank is ok with that but would like the upper of the two to return the user to the list of configurations rather than go to the next subtab. 

Only the lower of the two Next buttons should proceed to the next subtab.

**Comment by stevenFulgham** [comment]
That is an error on my part. There should not be two next buttons, only the one to navigate to the next section. I will fix it.
