### ISSUE TITLE
UX Feedback: Page Layouts

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#19]
Frank doesn't mind the two buttons to open both the layouts screen and the help window. He'd like it to be structured such that the user is both encouraged by the layout, and told specifically by some text, to click a Help (or similar) button before selecting the one which will open the page layouts. That way the help window opens first, then the user can move it to the side, etc. and then open the page layouts screen. 

Let's add an instructional text area above the buttons to explain the step. Use the content that's currently in the help window about "why do I need to do this?". Frank wants the button/link which opens the help window to be more explicit, have more of a call to action that it's first. So maybe a more vertical layout?
He also mentioned having this link/button move from object to object as the user marks them Done in the help window. Maybe a simple show/hide based on status. 

Also noted that the status of an object doesn't persist if the user leaves the screen. I'd like it to in case the admin gets logged out. we can use a new custom setting. 

Would like the object name much larger in the help window so the user is clear which object is being done. 

wasn't clear to me that I moved from page layouts to related lists. make the progression more prominent.

**Comment by stevenFulgham** [comment]
Rina is reworking flow for this page.

**Comment by rinaTaur** [comment]
Okay, here's an update, which will likely address #23 and #24 as well.

https://c.na30.visual.force.com/apex/UX_PageLayouts
![image](https://cloud.githubusercontent.com/assets/2474368/14608569/4972076a-0554-11e6-9615-9036a7f3a2c4.png)

https://c.na30.visual.force.com/apex/UX_Echo_ContactPageLayout
Object starter step (to launch page layout)
![image](https://cloud.githubusercontent.com/assets/2474368/14608599/66887b72-0554-11e6-8689-bb8ef0f4c389.png)

Object steps
![image](https://cloud.githubusercontent.com/assets/2474368/14608609/6fb193d2-0554-11e6-8ed9-2130e25064c5.png)
