### ISSUE TITLE
As an installing Admin I want to have all application setup and configuration steps on individual subtabs on the Echo Admin tab so that I can easily step through all of the config tasks and begin using the app

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#2]
This story is just the subtab structure for the Echo Admin VF tab. 

AC:
- [x] A user with permissions to view the Echo Admin tab can view the following subtabs:
 - Connect to MIR3
 - Default Device Priority 
 - Recipient Mappings
 - Page layouts
 - Workflow Rules
 - Search Layouts 
 - Getting Started
- [x] A user with permissions to view the Echo Admin tab can switch between the subtabs by clicking the name of each
- [x] A user with permissions to view the Echo Admin tab can navigate between the subtabs using Next and Previous buttons on each one.

**Comment by jengler74** [comment]
@stevenFulgham @rinaTaur should the first subtab, the Connect to MIR3 one, have a "Next" even before a configuration is created?

**Comment by stevenFulgham** [comment]
Yes. Sorry, missed that one.
