### ISSUE TITLE
Page Layout UI

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#21]
Frank doesn't mind the two buttons to open both the layouts screen and the help window. He'd like it to be structured such that the user is both encouraged by the layout, and told specifically by some text, to click a Help (or similar) button before selecting the one which will open the page layouts. That way the help window opens first, then the user can move it to the side, etc. and then open the page layouts screen.
Let's add an instructional text area above the buttons to explain the step. Use the content that's currently in the help window about "why do I need to do this?". Frank wants the button/link which opens the help window to be more explicit, have more of a call to action that it's first. So maybe a more vertical layout?
He also mentioned having this link/button move from object to object as the user marks them Done in the help window. Maybe a simple show/hide based on status.

**Comment by stevenFulgham** [comment]
I believe this has been added by Rina.

**Comment by jengler74** [comment]
I'd prefer to mark this as Done when it's been implemented in the dev org
