### ISSUE TITLE
Help window text sizing

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#23]
Would like the object name much larger in the help window so the user is clear which object is being done.

Also move the Why Do I have to do this? to the main window from the help window

**Comment by rinaTaur** [comment]
More of a universal approach, with the tabs informing navigation between objects:
![image](https://cloud.githubusercontent.com/assets/2474368/14608743/f2d572ce-0554-11e6-8658-9df4474c6184.png)

@stevenFulgham // @jengler74
