### ISSUE TITLE
Need a markerboard mockup of a new subtab for Search Settings

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#28]
with the addition of a second multi-select PL on Recipient Configurations, the existing subtab is getting overloaded and the page is getting sluggish. 

Would like a mockup of a new subtab, Search Settings, with Search Fields and Search Column Fields (new field) editable as a MSP for each object.

![image](https://cloud.githubusercontent.com/assets/7884339/14650574/39543a60-0621-11e6-9b1a-ac46473379ab.png)

**Comment by rinaTaur** [comment]
@jengler74 sure! Just to confirm, this is what I'm currently seeing for the Search Fields:
![image](https://cloud.githubusercontent.com/assets/2474368/14650935/ae840bde-063b-11e6-8b5b-a6a9feb34b1a.png)

That's a lot different than the screengrab you shared... may need a hangout to clarify?

**Comment by jengler74** [comment]
That's just Steven's first draft of the Search Fields. Disregard the
checkboxes. Should be an MSP with Available on the left and Selected on the
right, populated with all fields on the object. Frank's team also added the
ordering buttons to their MSP which we can pull from their packaging org if
need be.

On Tue, Apr 19, 2016 at 11:34 AM, Rina Henderson <notifications@github.com>
wrote:

> @jengler74 <https://github.com/jengler74> sure! Just to confirm, this is
> what I'm currently seeing for the Search Fields:
> [image: image]
> <https://cloud.githubusercontent.com/assets/2474368/14650935/ae840bde-063b-11e6-8b5b-a6a9feb34b1a.png>
>
> That's a lot different than the screengrab you shared... may need a
> hangout to clarify?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CodeScience/MIR3/issues/28#issuecomment-212060536>
>



-- 
Jeremy Engler | Director, ISV Product Management
_______________________

832 Cole Street

San Francisco, CA 94117

*C* 415-515-9429

*info@codescience.com* <hr@codescience.com>

*www.codescience.com <http://www.codescience.com/>*


*loathing cubicles since 2009* - We are hiring!
<http://codescience.com/careers/>

**Comment by rinaTaur** [comment]
@jengler74 - Here's the subtab for Search Options, with both Search Fields and Search Columns + instructional text to clarify what the user is configuring for each. The buttons would trigger Steven's modal as you described it above -- SLDS modal with the left and right MSP.

![image](https://cloud.githubusercontent.com/assets/2474368/14651900/e0fe9f80-063f-11e6-9b39-1e0a89705358.png)

**Comment by jengler74** [comment]
keep in mind that these fields are set per object so the user will need a
way to switch between objects to set them.

On Tue, Apr 19, 2016 at 12:03 PM, Rina Henderson <notifications@github.com>
wrote:

> @jengler74 <https://github.com/jengler74> - Here's the subtab for Search
> Options, with both Search Fields and Search Columns + instructional text to
> clarify what the user is configuring for each. The buttons would trigger
> Steven's modal as you described it above -- SLDS modal with the left and
> right MSP.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/2474368/14651900/e0fe9f80-063f-11e6-9b39-1e0a89705358.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CodeScience/MIR3/issues/28#issuecomment-212070910>
>



-- 
Jeremy Engler | Director, ISV Product Management
_______________________

832 Cole Street

San Francisco, CA 94117

*C* 415-515-9429

*info@codescience.com* <hr@codescience.com>

*www.codescience.com <http://www.codescience.com/>*


*loathing cubicles since 2009* - We are hiring!
<http://codescience.com/careers/>

**Comment by rinaTaur** [comment]
You are correct. Question for you, @jengler74, and for @stevenFulgham: 

Can the modal handle switching between objects, from a data / loading / technical perspective?

Here's my thinking:
I'd like to keep the buttons on this sub-tab to a minimum and have the object nav happen in the modal. That would likely look something like a left and right arrow in the header of the modal, with the header displaying the name of the object that's currently being edited, and possibly a little dropdown arrow to the right of the object name in case they need to switch to a specific object. The list of objects would, I assume, be generated dynamically, based on the columns that have been added within the Recipient Mapping sub-tab?

Save and Cancel buttons would be housed in the footer of the modal, in addition to the typical "X" to close the modal.

![image](https://cloud.githubusercontent.com/assets/2474368/14677411/9fc8e5b6-06df-11e6-8d96-55918606fc67.png)

**Comment by stevenFulgham** [comment]
The short answer is "Yes I can". 

Just some thoughts...
Is there a way we can map the Search Fields and Search Columns that is similar to the way we do recipient mappings? It seems like we have many variations vs similarities in how we handle user interaction. If you decide to go with the modal, can the "Search Options" tab items be horizontally aligned versus vertically. This would look like the Trial and Activate in the "Connect To Mir3" tab.

**Comment by stevenFulgham** [comment]
![wireframesearchoptions](https://cloud.githubusercontent.com/assets/17146094/14679089/73a89ef2-06e6-11e6-890c-2a86e1da76e2.jpg)

**Comment by rinaTaur** [comment]
@stevenFulgham I thought about that too actually. I think though it will be a bit busy. The nav I sketched is basically doing that same thing, in the same order as recipient mappings, but it's just hiding the adjacent "columns" of information. I think the page might get a bit busy otherwise... A modal focuses the experience, but we could basically do the same thing in the page without having to pop a modal... using overflow:hidden and having left to right nav.

If we did decide to consider the layout you sketched, I'd flip the side with the header, in keeping with Recipient Mappings. So, more like this:
![image](https://cloud.githubusercontent.com/assets/2474368/14680460/616f7274-06eb-11e6-93b2-1ab0eddaa35d.png)




Thoughts @jengler74?

**Comment by stevenFulgham** [comment]
I like it!

**Comment by jengler74** [comment]
I like Rina's last drawing with the exception of displaying the objects one at a time. My feeling on the Recipient Mappings page is that we should have done it one at a time because it's a sloooow page now. 
It's also an admin page that won't be visited often so I don't think it needs to be overbuilt. I don't think it should be in a modal as well if that's what the last drawing shows.
