### ISSUE TITLE
As an installing admin I want to authenticate to a MIR3 trial account so that I can start evaluating the app without purchasing first

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#3]
On the Connect to MIR3 subtab the user will perform the MIR3 authentication as it exists today. One option to a new user is to select a new 15-day trial account which will populate the Echo Notifications record with trial values and connect the user. This functionality already exists in the app. We are simply relocating and reformatting this step. 

AC:
- [x] A user is presented with a clear visual option to create a new trial account on the Connect to MIR3 subtab on the Echo Admin tab
- [x] Selecting the new trial option creates and populates an Echo Configuration record with the proper values (functionality already exists
- [x] A user can switch easily from using trial creds to production. JE: I'm forgetting if the trial creds become prod or if a new account has to be set up at that time. Answer = new creds
- [x] Hide the Device Priority button when editing the Active Configuration

Task:
- [x] locate Free Trial method/code to leverage

**Comment by rinaTaur** [comment]
Userflow of the Connect subtab within Admin Tab.
![mir3-connect](https://cloud.githubusercontent.com/assets/2474368/14195009/88b6fc3a-f782-11e5-9f7e-a7382ac8b35e.jpg)

**Comment by jengler74** [comment]
i figured out the error. It's because the post install script wasn't run in our dev org like it would in a customer's org. It populates several custom settings, which data is then in turn used in the Echo Configuration record. I manually entered the custom setting data and was able to create a new MIR3 trial from the app. 

![image](https://cloud.githubusercontent.com/assets/7884339/14266572/0df421ae-fa7e-11e5-9e88-b6b7623d282e.png)

From there, once I select "Cancel Trial" I am returned to the list of configurations but just the Name "Trial" is displayed for that config record. It's missing URL Base, API Version, User Name and Active Configuration. 

![image](https://cloud.githubusercontent.com/assets/7884339/14266597/31b7fdf4-fa7e-11e5-93fc-f9d22e1e3992.png)

**Comment by stevenFulgham** [comment]
The Trial not having a URL Base, API Version, User Name or Active Configuration value is the current behavior. See the image below.

![screen shot 2016-04-05 at 9 09 10 am](https://cloud.githubusercontent.com/assets/17146094/14282893/b6b6d94a-fb0e-11e5-8935-78dea3683c7e.png)
