### ISSUE TITLE
Add a Delete button to Recipient Configurations

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#34]
each object should be able to be deleted with a button/link on each column

**Comment by rinaTaur** [comment]
For some reason, I thought it was mentioned that once added, the objects would always be added. Is that incorrect? If it's correct, perhaps simply a "hide" button might be needed.

**Comment by jengler74** [comment]
add Delete button at bottom of each column EXCEPT for Lead, Contact, User

show a confirmation dialogue before deleting the record

**Comment by jengler74** [comment]
so the existing app does allow for Deleting these records, it's just the standard "Del" link next to each record in the standard list view on the tab. 

![image](https://cloud.githubusercontent.com/assets/7884339/15080028/d2e0d628-1370-11e6-8f59-e51bdfb62f20.png)

regardless, it's done now. thx
