### ISSUE TITLE
picklists on Recipient Mappings subtab are not pulling all fields from the object

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#35]
On Contacts, I can't select the custom text field SMS__c to map to the MIR3 SMS field. Looks like the picklists are only pulling the same type of field as the MIR3 field, i.e. only pulling SF fields of type Email for the MIR3 email fields. 
The previous page showed all standard and custom fields on the object 

![image](https://cloud.githubusercontent.com/assets/7884339/14720999/f684e29a-07b8-11e6-9850-42dbf2b48335.png)

![image](https://cloud.githubusercontent.com/assets/7884339/14721006/fdf56874-07b8-11e6-8027-9a278afae880.png)

**Comment by jengler74** [comment]
the Lead picklist is not showing all fields. There are many not showing that exist in the org. 

![image](https://cloud.githubusercontent.com/assets/7884339/14922382/278a86a4-0dec-11e6-8f5f-ce8f38b0e35b.png)

![image](https://cloud.githubusercontent.com/assets/7884339/14922388/31b54164-0dec-11e6-98f3-7d8852ae48d0.png)

**Comment by stevenFulgham** [comment]
I know we discussed this but I want to be sure. Is this for all fields or just SMS? Try it now.

**Comment by jengler74** [comment]
for all fields, you've got it now

![image](https://cloud.githubusercontent.com/assets/7884339/14923271/24320bd0-0df1-11e6-961a-8f2f6340ad38.png)
