### ISSUE TITLE
As an installing admin I want to authenticate to a MIR3 production account so that I can start using the product

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#4]
This is simply leveraging the existing New Echo Configurations VF page, same fields, but with the SLDS look and feel. 

AC:
- [x] A user is presented with a clear option to enter production credentials from MIR3 on the Connect to MIR3 subtab on the Echo Admin tab
- [x] A user is presented with the existing authentication fields from Echo Configurations that are captured in the app today. 
- [x] Saving these values creates a new Echo Configuration record with Active = TRUE
- [x] After a user has selected Production settings and saved the configuration values, they may add additional Configurations, using the same New Configuration UI as the first time
- [x] All production Configurations can be viewed in the existing table
- [x] The "Active" column has an action to make that particular Configuration.Active=TRUE
- [x] All Echo Configuration fields are presented in the SLDS

**Comment by rinaTaur** [comment]
![mir3-connect](https://cloud.githubusercontent.com/assets/2474368/14195046/de6e4854-f782-11e5-9257-6401a87f0681.jpg)

**Comment by stevenFulgham** [comment]
Clicking trial or trying to license product are not working. I get this error:

**Visualforce Error**
System.NullPointerException: Argument 1 cannot be null
Error is in expression '{!addNewTrialConfig}' in page connecttomir3: Class.INSFConfiguration.AddDivision: line 211, column 1
Class.INSFConfiguration.addNewTrialConfig: line 149, column 1

Class.INSFConfiguration.AddDivision: line 211, column 1
Class.INSFConfiguration.addNewTrialConfig: line 149, column 1

Once I have fixed the errors, steps 3 and 4 for this ticket will be complete.
