### ISSUE TITLE
WF progress naming

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#41]
On the WF rules tab, can you make the progress steps the name of the two workflow rules themselves? rather than "Creating the WF Rule" and "Repeat..."

![image](https://cloud.githubusercontent.com/assets/7884339/14750220/7fd7ab1c-0878-11e6-84c7-784f525ed277.png)

**Comment by stevenFulgham** [comment]
Im not seeing the workflow names you want to use in Create -> Workflows. Can you post what you would like them to be or is this dynamic based on the names of the workflows they setup?

**Comment by jengler74** [comment]
they are the Start Notifications Scheduler and the End Notifications Scheduler workflow rules. 

Doesn't need to be dynamic. We're recommending that they replace these rules with triggers anyway.
