### ISSUE TITLE
Help window Title

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#42]
the help window's title is currently "Dock Panel Test". Can that be "Setup Assistant"?

**Comment by jengler74** [comment]
@stevenFulgham I'm talking about up top in the help window where it says Dock Panel Test

![image](https://cloud.githubusercontent.com/assets/7884339/14922307/b7c4d31a-0deb-11e6-88ca-447b8136270b.png)

**Comment by stevenFulgham** [comment]
![screen shot 2016-04-29 at 12 41 09 pm](https://cloud.githubusercontent.com/assets/17146094/14922820/afb406ca-0e07-11e6-96eb-17ddf7a4f501.png)

**Comment by stevenFulgham** [comment]
Im not getting that.

**Comment by stevenFulgham** [comment]
Try it now

**Comment by jengler74** [comment]
weird, maybe my cache
