### ISSUE TITLE
As an installing admin I want a subtab to guide me through the Page Layout edits so I can quickly setup the app

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#5]
AC:
- [x] The Page Layouts subtab displays buttons for each of the objects which need page layout configuration post-install: Contact, Lead, Cases, Campaigns. 
- [x] Selecting an object's button does several things:
   - [x] Opens to that object's Page Layouts page in Setup in a new tab

**Comment by jengler74** [comment]
Rina to check in with Dan on floating window Next/previous controls

**Comment by stevenFulgham** [comment]
I am receiving this error when I try to navigate to Leads, Campaigns or Cases:

**Insufficient Privileges**
_You do not have the level of access necessary to perform the operation you requested. Please contact the owner of the record or your administrator if access is necessary. For more information, see Insufficient Privileges Errors. _
