### ISSUE TITLE
Update GetSelectedObjectFields in Recipient Mappings class

### ISSUE THREAD

**Issue by stevenFulgham** [CodeScience/MIR3#53]
Copy logic from GetSelectedObjectFields in packaging org into the dev org.

**Comment by jengler74** [comment]
@stevenFulgham you should get started on this. if you go over 4 hours let me know.

**Comment by stevenFulgham** [comment]
Just to clarify, the "Account.Name" field on the contact object should display as "Account Name".  When persisting the "Account Name" field, it should be persisted as "Account.Name". Are there any other conditions that I did not cover?

**Comment by jengler74** [comment]
Yes, picklist displays "Account Name" for Contacts rather than Account ID. 

The Echo_Recipient field is Company_Account_Name__c and you'll persist whatever their code is currently putting there. 

From this chunk of code that looks correct to me:

     if(setSelectedFields != null && setSelectedFields.size() > 0){
                for(String key : setSelectedFields){
                    if(strStandardObject == 'Contact' && key == 'account.name'){
                        
                        optionsSelectedFieldNames.add(new SelectOption(key ,'Account Name'));
                    }
                    else{
                        strFieldLabel = fnBindFieldLabel(key);                                
                        optionsSelectedFieldNames.add(new SelectOption(key,strFieldLabel));
                    }
                }
            }
           
            if(!string.IsBlank(strSearchColumnFields)){
                CheckExistingField(strSearchColumnFields.split(','),'Searchcolumnfield');
                setSelectedColumnFields =  fnBindSelectedFields(strSearchColumnFields);    
            }
            
            if(setSelectedColumnFields != null && setSelectedColumnFields.size() > 0){
                 String fieldLabel = '';
                 for(String key : setSelectedColumnFields){
                    if(strStandardObject == 'Contact' && key == 'account.name'){                        
                        optionsSelectedSearchColumnField.add(new SelectOption(key ,'Account Name'));
                    }
                    else{
                        fieldLabel = fnBindFieldLabel(key);                  
                        optionsSelectedSearchColumnField.add(new SelectOption(key,fieldLabel));
                   }
                }
            }           
            
            if(strStandardObject == 'Contact' && !setSelectedFields.contains('account.name')){
                optionSearchAllField.add(new SelectOption('account.name','Account Name'));
            }
            if(strStandardObject == 'Contact' && !setSelectedColumnFields.contains('account.name')){
                optionsAllSearchColumnField.add(new SelectOption('account.name','Account Name'));
            }
            if(strStandardObject == 'Contact' && setSelectedFields.contains('account.name')){
                mapAllFields.put('account.name','Account Name');
            }
            if(strStandardObject == 'Contact' && setSelectedColumnFields.contains('account.name')){
                mapAllFields.put('account.name','Account Name');
            }

We then assume that their code reads that value correctly on the Recipient Query page

**Comment by jengler74** [comment]
when i select "Account Name" from the Contact picklist and map it to First Name on the MIR3 side, the object is still persisting "accountid" which then makes the Search Options page include it. 

It should be persisting "account.name" per the code above. Search Options tab should read it as "Account Name" for Contacts when selecting Search Fields and Search Column Fields.

**Comment by stevenFulgham** [comment]
Ok I understand now. 
This was confusing me.
_**The Echo_Recipient field is Company_Account_Name__c and you'll persist whatever their code is currently putting there.**_

**Comment by stevenFulgham** [comment]
I was persisting Account.Name for the Company_Account_Name__c. I removed that and now I am persisting it for any Object field that has Account Name selected.

**Comment by jengler74** [comment]
I can see that. That was my fault. 

Now, in packaging it's displaying on Recip Mappings and persisting correctly, akaik, but Search Options shows a blank
