### ISSUE TITLE
final copy edits on Page Layouts help

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#56]
see final edits in Rina's doc:

https://docs.google.com/document/d/1mAo0poJ9bUJtXvr5R-W052KHmNAb9rqc3ZLtkiiSY8Q/edit

**Comment by stevenFulgham** [comment]
I have updated the pages. I have also left remarks in the document that I need clarity on.

**Comment by jengler74** [comment]
putting back to In Progress just until all loose ends are tied up

**Comment by stevenFulgham** [comment]
Ok. This card is complete.
