### ISSUE TITLE
As an installing admin I want a subtab to create my Recipient Mappings so that I have one easy place to set them up

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#6]
AC:
- [x] Subtab for Recipient Mappings displays several columns of data to make mapping multiple objects easier
- [x] Left hand column is static for MIR3 Fields
- [x] Next column is Lead Fields, with a picklist of all Lead Fields for each MIR3 Field
- [x] Next column is Contact Fields, with a picklist of all Contact Fields for each MIR3 Field
- [x] Next column is User Fields, with a picklist of all User Fields for each MIR3 Field
- [x] Lead, Contact, and User default mappings are loaded
- [x] User can add new Recipient Mappings for any other objects
- [x] New object mappings are added to the page alongside the default objects
- [x] Save, Save & Next buttons persist all mappings to the object (and Next moves to the next step)

Question: where are the default mappings (lead, contact, user) stored today?

**Comment by jengler74** [comment]
@rinaTaur @stevenFulgham Search Fields - heard back from Frank on the importance of the Search Fields field; it's so that the admin can select a subset of all of the object's fields for their users to select from, helping to narrow the list for those users from potentially hundreds of fields. 

If that's the case, can we have another view of the same table from the mockup that is a grid of checkboxes that marks the field as a SearchField and is then persisted to the object?

**Comment by rinaTaur** [comment]
First iteration (based on initial prototype demo). @jengler74 @stevenFulgham Does this address everything? I have a couple questions labeled in the userflow, and with the note above about search fields, may need to talk some of this outloud with you guys.
![mir3-recmapping](https://cloud.githubusercontent.com/assets/2474368/14195664/fc8c8e7a-f789-11e5-98d8-776d74f39b51.jpg)

**Comment by stevenFulgham** [comment]
1. I need to know what the common objects are on the initial load of the page.
2. Rina is going to create a version 2 of her wireframe, so I know exactly what she wants in the UI.

**Comment by jengler74** [comment]
There's a post-install script which populates the three default objects' recipient mappings which are defined in this story above. This part of that code populates all three with the following values, so on the initial load the page should just be reading the Recipient_Configuration__c records which exist in the org:

   Echo_Recipient_Configuration__c objERCContact = New Echo_Recipient_Configuration__c();
            objERCContact.Name = 'Contact'; 
            objERCContact.Object_API_Name__c = 'Contact'; 
            objERCContact.Object_Key_Prefix__c = findObjectKeyPrefix('Contact');
            objERCContact.First_Name__c = 'firstname'; 
            objERCContact.Last_Name__c = 'lastname'; 
            objERCContact.Work_Email__c = 'email';
            objERCContact.Home_Email__c = 'home_email__c';
            objERCContact.Work_Phone__c = 'phone';
            objERCContact.Home_Phone__c = 'homephone';
            objERCContact.Mobile__c = 'mobilephone';             
            objERCContact.Fax__c = 'Fax';
            objERCContact.Country__c = 'mailingcountry';
            objERCContact.State__c = 'mailingstate';
            objERCContact.City__c = 'mailingcity';
            objERCContact.Zip_Code__c = 'mailingpostalcode';
            objERCContact.Title__c = 'title';
            objERCContact.Search_Object_Fields__c = 'email,firstname,homephone,lastname,mobilephone,phone,fax';
            if(Schema.sObjectType.Echo_Recipient_Configuration__c.iscreateable()){
                Insert objERCContact;
            }
            
            Echo_Recipient_Configuration__c objERCLead = New Echo_Recipient_Configuration__c();
            objERCLead.Name = 'Lead'; 
            objERCLead.Object_API_Name__c = 'Lead'; 
            objERCLead.Object_Key_Prefix__c = findObjectKeyPrefix('Lead');
            objERCLead.First_Name__c = 'firstname'; 
            objERCLead.Last_Name__c = 'lastname'; 
            objERCLead.Work_Email__c = 'email';
            objERCLead.Work_Phone__c = 'phone';
            objERCLead.Mobile__c = 'mobilephone';
            objERCLead.Fax__c = 'fax';
            objERCLead.Company_Account_Name__c = 'company';
            objERCLead.Country__c = 'country';
            objERCLead.State__c = 'state';
            objERCLead.City__c = 'city';
            objERCLead.Zip_Code__c = 'postalcode';
            objERCLead.Title__c = 'title';
            objERCLead.Search_Object_Fields__c = 'city,company,country,email,fax,firstname,lastname,industry,mobilephone,phone,postalcode,state,title';
            if(Schema.sObjectType.Echo_Recipient_Configuration__c.iscreateable()){
                Insert objERCLead; 
            }
            
            Echo_Recipient_Configuration__c objERCUser = New Echo_Recipient_Configuration__c();
            objERCUser.Name = 'User'; 
            objERCUser.Object_API_Name__c = 'User'; 
            objERCUser.Object_Key_Prefix__c = findObjectKeyPrefix('User');
            objERCUser.First_Name__c = 'firstname'; 
            objERCUser.Last_Name__c = 'lastname'; 
            objERCUser.Work_Email__c = 'email';
            objERCUser.Home_Phone__c = 'phone';
            objERCUser.Mobile__c = 'mobilephone';
            objERCUser.Fax__c = 'fax';
            objERCUser.Company_Account_Name__c = 'companyname';
            objERCUser.Country__c = 'country';
            objERCUser.State__c = 'state';
            objERCUser.City__c = 'city';
            objERCUser.Zip_Code__c = 'postalcode';
            objERCUser.Title__c = 'title';
            objERCUser.Search_Object_Fields__c = 'firstname,lastname,email,phone,mobilephone,fax,companyname,country,state,city,postalcode,title';
            if(Schema.sObjectType.Echo_Recipient_Configuration__c.iscreateable()){
                Insert objERCUser;   
            }

**Comment by thepartycow** [comment]
Can I just say how much I love watching you all work? This is great collaboration and detail on this story. Nice work team.

**Comment by jengler74** [comment]
Here we were maintaining comment discipline, staying on topic, and @thepartycow has to litter it with praise and compliments. 

With that said, I had a great walkthrough with Frank today. As relates to this story:

He still likes the table design as long as we can figure out how to make the left column fixed. 

He's also fine with the modal for Search Fields prompted by a button at the bottom of each object's column. 
He will be adding a second, similar selection which will define the column headers that a user sees in the custom query tool that his team has built. We will add that second setting to this same modal when ready. 

no other notes on this subtab. rip it up.

**Comment by stevenFulgham** [comment]
1. SLDs UI
2. Reworked Server Side Code
3. Added Exception Handlers
4. Cancel reloads the page
5. One save instead of a save at the bottom of every object
6. No need for a save and next. Save will persist every object on the page.

Question: Do I need to add Unit Test for the Server-Side Logic I created? (Not in Scope)

**Comment by jengler74** [comment]
marking as done and moving the modal for RecipientConfiguration.SearchFields__c to a new story
