### ISSUE TITLE
Navigation on subtabs getting "page not found"

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#63]
odd behavior in a test org. I can give you acess to repro:

User goes to the Echo Admin tab

User goes to Recipient Mappings subtab by clicking the name

First time works, Recipient Mappings renders.

Click Recipient Mappings subtab name again

page gives: Page RecipientMappings does not exist 

First time the URL is: https://echonotify.na30.visual.force.com/apex/RecipientMappings

second time it switches to: https://c.na30.visual.force.com/apex/RecipientMappings

seems like a namespace issue because this works in the packaging org, looks like the URL drops the namespace the second time around

**Comment by jengler74** [comment]
appears to do this on the **second** subtab to which the user goes, regardless of which one.

**Comment by stevenFulgham** [comment]
I’ll fix it.

Steven Fulgham
UI Engineer
_______________________________


loathing cubicles since 2009 - we are hiring! <http://codescience.com/careers>
CHATTANOOGA | ATLANTA | SAN FRANCISCO
D: 678.333.3908
codescience.com <http://www.codescience.com/>
