### ISSUE TITLE
Page CaseRemoteSetupAssistance does not exist

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#64]
after packaging and installing to a QA org, the first time when I step through the page layout wizard, the Done button on each object gives me a DNE error. i can close and reopen and it's there. 

does not do this in packaging org. works as expected
 
![image](https://cloud.githubusercontent.com/assets/7884339/15337581/5fac812e-1c31-11e6-8635-9eedd6068cd8.png)

![image](https://cloud.githubusercontent.com/assets/7884339/15337597/6faf790a-1c31-11e6-890a-de93d216f1cb.png)

**Comment by jengler74** [comment]
@stevenFulgham can I ask you to leave a brief description of what you did to resolve this or any issue? Emphasis on brief. It's good for me to have context on the resolution in case something similar comes up or the client asks me. thank you!

**Comment by stevenFulgham** [comment]
I missed these anchor tags when I replaced all the links in the application with the apex outputLink tag.
