### ISSUE TITLE
The "Open {Objectname} Page Layout" button is requiring login when already logged in

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#69]

**Comment by jengler74** [comment]
![image](https://cloud.githubusercontent.com/assets/7884339/15377118/26d12c14-1d0e-11e6-8f74-7abd3244adb1.png)

the first time I open the object's page layout I'm asked to re-authenticate to salesforce. it had been opening properly before.

**Comment by jengler74** [comment]
same for workflow

**Comment by stevenFulgham** [comment]
Im hoping this was just a link problem and not a CORS issue. I changed the button to an apex outputLink.

I have also updated the Packing Org to reflect the changes.

**Comment by jengler74** [comment]
waiting to verify in QA5, blocked by unit test failures
