### ISSUE TITLE
As an installing Admin I want an easy way to send a sample notification to myself so that I can fully evaluate the product. 

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#7]
AC:
- [ ] User can select a single button which will send a canned notification to them
- [ ] Sample notification sends the sample to the running User's email and phone, if present
- [ ] Admin page displays a link to the Notification record so the user can review it and the response

Frank says that they have code that will do this already

**Comment by stevenFulgham** [comment]
I have changed the estimate on this task. I believe this should be an epic with the following stories.

1. Finish the logic to allow automated test
2. Create UI for missing data such as e-mail or phone number
3. Create FrontEnd logic for new UI elements
4. Create Exception Handlers and Notifications for persistence and errors
5. Test Feature
