### ISSUE TITLE
Search Options click behavior

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#71]
Frank noted that when the user selects a fieldname in any box, available or selected, fields or columns, the defauly behavior is to multi-select each one without holding any key down to do so. 

He would like this removed if possible so that the user needs to hold command/apple to multi-select

**Comment by stevenFulgham** [comment]
Added event listener for command key mac and shift key PC. Added styling for legacy select as well. These changes have been made in the packaging org as well.

**Comment by jengler74** [comment]
holding apple/command does a multi-select

however, Shift+click does not fill in to last selected, it's acting like a command+click

also:

click an option first
then without using any keys, click another

expected: selection moves to the new option
actual: first selection will not unselect and the new option will not select

**Comment by stevenFulgham** [comment]
Added javascript logic to address each issue. Updated packaging.
