### ISSUE TITLE
Echo Config Name requirement not being enforced on page

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#80]
a user can save a new Echo Config without entering a Name. Should behave like User Name and # of Recipients. 

![image](https://cloud.githubusercontent.com/assets/7884339/15549134/1678166e-2260-11e6-80e4-407182f972bd.png)

**Comment by stevenFulgham** [comment]
Added required to the apex input for Echo configuration name. Added css to fix red required indicator bar to the left of the input expanding past the input. Added css to fix the space above the error message. Updated Packaging.
