### ISSUE TITLE
After using Save & Next on New Echo Config: Confirm Password not nulled out

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#81]
when a user enters a new Echo Config and uses Save & Next, the page comes back but the Confirm Password field still has the previously used value and should be nulled out. 

![image](https://cloud.githubusercontent.com/assets/7884339/15549578/08b03078-2262-11e6-83b1-695fd2e3f312.png)

**Comment by stevenFulgham** [comment]
Blanked the Confirm password field on successful save in the server side code. This code was 50% done in Packaging. Not sure why they didn't complete it. At any rate, Packaging has been updated as well.
