### ISSUE TITLE
Long object names on Search Options

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#83]
If a user maps an object with a long name on Recip Mappings, the object Name on Search Options is crashing into the MSP fields on the same row. 

Similarly, make sure to persist the Label of the newly mapped object from RecipMapp so that we don't get underscores, etc. and can possibly line break on the spaces

![image](https://cloud.githubusercontent.com/assets/7884339/15549822/4ef08190-2263-11e6-982c-14f725481834.png)

**Comment by stevenFulgham** [comment]
Added javascript to fix the issues with long text. Added css to wrap text in column. Updated Packaging org as well.

**Comment by jengler74** [comment]
Can the namespace be truncated from the beginning? Not all objects will have them. Maybe look at their controller because the field labels don't have the namespace before them. 

![image](https://cloud.githubusercontent.com/assets/7884339/15557186/8f205736-2286-11e6-9c06-b2b55ec6ddb0.png)

**Comment by jengler74** [comment]
moving issue to new ticket: persist the Object Label to RecipConfig.Name
