### ISSUE TITLE
RecipMapp: Field changes not saved in memory while new object mapped

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#92]
to repro:

change a field mapping in an existing object, do not save

add a new object mapping

expected: changed field is held in memory and can be saved without re-mapping it

actual: the changed field is marked yellow to be saved but the value was dropped when the new object was added.

![image](https://cloud.githubusercontent.com/assets/7884339/15592382/230743ca-2358-11e6-98d9-f01173d60a8e.png)

**Comment by stevenFulgham** [comment]
Option values weren't being set to "selected" when a user made a new selection. Added some javascript to fix the problem. Updated packaging.
