### ISSUE TITLE
BLOCKER: Error trying to reach RecipMapp and SearchOptions in pkg

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#93]
Attempt to de-reference a null object 
An unexpected error has occurred. Your development organization has been notified.

both the RecipMapp and SearchOptions subtabs are giving the above error when a user selects one.

**Comment by stevenFulgham** [comment]
Can you reach out to me on this one. Hangout or slack is fine. I need more info. Line # etc.

**Comment by jengler74** [comment]
That's all the message there was.

On Thursday, May 26, 2016, Steven Fulgham <notifications@github.com> wrote:

> Can you reach out to me on this one. Hangout or slack is fine. I need more
> info. Line # etc.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeScience/MIR3/issues/93#issuecomment-222039838>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHhOM5TvA48hIjV0gBCW79uxVMmuwNcxks5qFks_gaJpZM4IoBW5>
> .
>


-- 
Jeremy Engler | Director, ISV Product Management
_______________________

832 Cole Street

San Francisco, CA 94117

*C* 415-515-9429

*info@codescience.com* <hr@codescience.com>

*www.codescience.com <http://www.codescience.com/>*


*loathing cubicles since 2009* - We are hiring!
<http://codescience.com/careers/>

**Comment by stevenFulgham** [comment]
When you package dev are you getting this same error?
