### ISSUE TITLE
SearchOptions: multi-select does not keeping order of fields when re-ordering

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#94]
![image](https://cloud.githubusercontent.com/assets/7884339/15592509/4223d6a0-2359-11e6-9c00-eaf5ca03b766.png)

to repro:
on Search Options take an object with a lot of fields (you should rebase the controller b/c their code now returns ALL fields from an object on Search Options, not just the ones selected on Recipient Mappings) and have several fields in the selected box

now multi-select two fields and select the TOP button

expected: the selected fields move to the top, in consistently either the relative order they were just in or the order in which they were selected. 

actual: It appears to be randomly either one at present.

**Comment by stevenFulgham** [comment]
Applied same logic as the "Move Up and Done One" function to the "Move Absolute Top and Bottom" function. Updated Packaging.
