### ISSUE TITLE
SearchOptions: previously saved fields staying green after save

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#95]
![image](https://cloud.githubusercontent.com/assets/7884339/15592581/c6ab5646-2359-11e6-880c-ab815effa290.png)

client would like the previously saved fields to drop the green outline after a subsequent save which didn't involve them.

**Comment by stevenFulgham** [comment]
Created Remote service to get updated search values. Added javascript to remove green outlines after successful save when user makes additional changes. Requires page to call remote service to compare saved values since last modified. Updated Packaging.
