### ISSUE TITLE
SearchOptions not saving consistently

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#96]
![image](https://cloud.githubusercontent.com/assets/7884339/15592659/54eda7c4-235a-11e6-8eaf-3cc52688ef9a.png)

in my own testing I kept adding all fields from one object to the Selected, saved and refreshed the page to have random fields move back to unselected. 

also verified that after removing all selected fields from an object and saving, the object still has all fields in the SearchFields that I just removed. 

seems like it's not nulling out removed fields.

**Comment by stevenFulgham** [comment]
Needed to remove check for empty string on server side.
