### ISSUE TITLE
SearchOptions: selecting two adjacent options disabled the down arrows

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#97]
![image](https://cloud.githubusercontent.com/assets/7884339/15592757/2f55fc68-235b-11e6-91b0-4d0864a910c4.png)

to repro:
on SearchOptions select two fields next to each other in any box
attempt to move them down

only up works with more than one

**Comment by stevenFulgham** [comment]
Added Javascript logic to move items properly. I Updated Packaging as well.
