### ISSUE TITLE
RecipMapp: Contact.Phone and Contact.Fax not appearing in picklists

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#98]
checked FLS and both fields are viewable by all profiles. other phone type fields are showing up. 

Fax missing:
![image](https://cloud.githubusercontent.com/assets/7884339/15616016/277db7e2-23f6-11e6-837e-900f6c298f04.png)

Phone missing:
![image](https://cloud.githubusercontent.com/assets/7884339/15616028/348885ca-23f6-11e6-921b-461c7ca2b121.png)

**Comment by stevenFulgham** [comment]
This is for Recipient Mappings correct?

**Comment by jengler74** [comment]
yes, sorry

**Comment by stevenFulgham** [comment]
These items are being mapped. However, the schema has the text value as "Business Fax" and "Business Phone".

![screen shot 2016-05-31 at 5 00 00 pm](https://cloud.githubusercontent.com/assets/17146094/15690419/6aa42598-2751-11e6-85fd-8910ebedddd3.png)

![screen shot 2016-05-31 at 5 00 42 pm](https://cloud.githubusercontent.com/assets/17146094/15690423/6fd256a2-2751-11e6-8bba-8f45aa4b03d4.png)

**Comment by jengler74** [comment]
that would explain why I couldn't find a field with that name. thought I was losing my mind. they do some interesting things in the app. this is bad UX to me.
