### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by jengler74** [CodeScience/MIR3#99]
#
Class Name
Method
Errors
Stack Trace
1
TestCtrlSearchOptions
Test_GetFieldLabel
System.NullPointerException: Attempt to de-reference a null object
Class.EchoNotify.ctrlSearchOptions.GetSearchFields: line 76, column 1
Class.EchoNotify.ctrlSearchOptions.<init>: line 54, column 1
Class.EchoNotify.TestCtrlSearchOptions.Test_GetFieldLabel: line 37, column 1
2
TestCtrlSearchOptions
Test_PersistSearchOptions
System.AssertException: Assertion Failed: Expected: firstname, Actual: firstname,pager_number__c,sms__c
Class.EchoNotify.TestCtrlSearchOptions.Test_PersistSearchOptions: line 60, column 1
3
TestCtrlSearchOptions
Test_GetSearchFields
System.NullPointerException: Attempt to de-reference a null object
Class.EchoNotify.ctrlSearchOptions.GetSearchFields: line 76, column 1
Class.EchoNotify.ctrlSearchOptions.<init>: line 54, column 1
Class.EchoNotify.TestCtrlSearchOptions.Test_GetSearchFields: line 10, column 1
4
TestRecipientsMappings
 
line 93, column 30: Constructor not defined: [RecipientMappingsConfiguration.SavedObjItem].&lt;Constructor&gt;(String, String, String, String, String, String, String, String, String, String, String, String, String)

**Comment by stevenFulgham** [comment]
Echo Mir3 code changes are conflicting with the test. For instance, you can no longer delete contact, lead or user, which I was doing in the setup of my test. Unit test are working in packaging.
